<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Product>Indicadores de movimiento</Product>
    <Version>0.1.0</Version>
    <Deterministic>true</Deterministic>
    <NeutralLanguage>es-ES</NeutralLanguage>
  </PropertyGroup>
</Project>
